# Missão individual

Escolha um arquivo:

- `clientes_sujo.csv`
- `filmes_sujo.csv`

Repita o processo:

1. Abra o arquivo.
2. Investigue.
3. Trate nulos.
4. Remova duplicados.
5. Padronize textos.
6. Corrija tipos.
7. Corrija valores inválidos.
8. Valide.
9. Salve uma versão tratada.

## 1. Importando o Pandas

In [1]:
import pandas as pd

## 2. Abrindo o dataset

In [2]:
df = pd.read_csv("filmes_sujo.csv")
df.head()

             Filme   Ano             Genero  NotaIMDb  DuracaoMin Infantil
0     Interestelar  2014  Ficção Científica       8.7         169      Não
1        Toy Story  1995          animação        8.3          81      Sim
2         Parasita  2019              Drama       8.5         132      Não
3  Divertida Mente  2015           Animação       NaN          95      Sim
4           Matrix  1999  Ficção Científica       8.7         136      Não

## 3. Investigação inicial

Ainda não corrija nada. Primeiro descubra os problemas.

In [3]:
df.shape

(11, 6)

In [4]:
df.columns

Index(['Filme', 'Ano', 'Genero', 'NotaIMDb', 'DuracaoMin', 'Infantil'], dtype='object')

In [5]:
df.dtypes

Filme          object
Ano            object
Genero         object
NotaIMDb      float64
DuracaoMin      int64
Infantil       object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Filme       11 non-null     object
 1   Ano         11 non-null     object
 2   Genero      11 non-null     object
 3   NotaIMDb    10 non-null     float64
 4   DuracaoMin  11 non-null     int64
 5   Infantil    11 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 660.0+ bytes

In [8]:
df.describe()

        NotaIMDb  DuracaoMin
count  10.000000   11.000000
mean    8.390000  114.909091
std     0.310734   75.516163
min     7.900000  -90.000000
25%     8.225000   97.500000
50%     8.450000  132.000000
75%     8.675000  165.500000
max     8.700000  180.000000

In [7]:
df.isnull().sum()

Filme         0
Ano           0
Genero        0
NotaIMDb      1
DuracaoMin    0
Infantil      0
dtype: int64

In [37]:
df.duplicated().sum()

np.int64(0)

## 4. Tratando valores nulos

In [14]:
nota = df["NotaIMDb"].mean()
print("NotaIMDb:", nota)

NotaIMDb: 8.39

In [56]:
duracao = df["DuracaoMin"].mean()
print("DuracaoMin", duracao)

DuracaoMin 129.4

In [15]:
df["NotaIMDb"] = df["NotaIMDb"].fillna(nota)

In [16]:
df.isnull().sum()

Filme         0
Ano           0
Genero        0
NotaIMDb      0
DuracaoMin    0
Infantil      0
dtype: int64

## 5. Removendo duplicados

In [17]:
df[df.duplicated()]

           Filme   Ano             Genero  NotaIMDb  DuracaoMin Infantil
10  Interestelar  2014  Ficção Científica       8.7         169      Não

In [18]:
df = df.drop_duplicates()

print("Duplicados restantes:", df.duplicated().sum())

Duplicados restantes: 0

## 6. Padronizando textos

In [20]:
f["Genero"] = df["Genero"].astype(str).str.strip().str.title()

/tmp/ipykernel_523/3246830845.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Genero"] = df["Genero"].astype(str).str.strip().str.title()

## 7. Corrigindo tipos de dados

In [60]:
df['Ano'] = df['Ano'].replace('2023', 2023)

df['Ano'] = pd.to_numeric(df['Ano'], errors='coerce')

df['Ano'] = pd.to_datetime(
    df['Ano'],
    format='%Y',
    errors='coerce'
)

In [43]:
df['Ano'] = pd.to_datetime(df['Ano'], errors='coerce').dt.year
df.dtypes

/tmp/ipykernel_523/2814148072.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ano'] = pd.to_datetime(df['Ano'], errors='coerce').dt.year

Filme          object
Ano             int32
Genero         object
NotaIMDb      float64
DuracaoMin      int64
Infantil       object
dtype: object

## 8. Localizando valores inválidos

In [22]:
df[df["DuracaoMin"] < 0]

   Filme   Ano   Genero  NotaIMDb  DuracaoMin Infantil
5  Shrek  2001  Comédia       7.9         -90      Sim

## 9. Corrigindo valores inválidos

As decisões abaixo são didáticas. Em projetos reais, consulte as regras do negócio.

In [57]:
df.loc[5, "DuracaoMin"] = 129.4

/tmp/ipykernel_523/2009395972.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '129.4' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[5, "DuracaoMin"] = 129.4

In [31]:
df.loc[8, "Infantil"] = 'Sim'

## 10. Validação final

In [30]:
print("Valores nulos:")
print(df.isnull().sum())

print("\nDuplicados:", df.duplicated().sum())

Valores nulos:
Filme         0
Ano           0
Genero        0
NotaIMDb      0
DuracaoMin    0
Infantil      0
dtype: int64

Duplicados: 0

In [33]:
df.describe()

        NotaIMDb  DuracaoMin
count  10.000000   10.000000
mean    8.359000  129.400000
std     0.291222   33.413903
min     7.900000   81.000000
25%     8.225000  102.250000
50%     8.395000  131.000000
75%     8.575000  155.500000
max     8.700000  180.000000

In [34]:
df.head(10)

,Filme,Ano,Genero,NotaIMDb,DuracaoMin,Infantil
0,Interestelar,2014,Ficção Científica,8.70,169,Não
1,Toy Story,1995,Animação,8.30,81,Sim
2,Parasita,2019,Drama,8.50,132,Não
3,Divertida Mente,2015,Animação,8.39,95,Sim
4,Matrix,1999,Ficção Científica,8.70,136,Não
5,Shrek,2001,Comédia,7.90,109,Sim
6,Oppenheimer,dois mil e vinte e três,Drama,8.40,180,Não
7,Avatar,2009,Ficção Científica,7.90,162,Não
8,Procurando Nemo,2003,Animação,8.20,100,Sim
9,Cidade de Deus,2002,Drama,8.60,130,Não

## 11. Salvando o dataset tratado

In [65]:
df.to_csv("filmes_tratado.csv", index=False)


df['Ano'] = df['Ano'].replace('dois mil e vinte e três', 2023)

df['Ano'] = pd.to_numeric(df['Ano'], errors='coerce')

df.dtypes

Filme          object
Ano             int32
Genero         object
NotaIMDb      float64
DuracaoMin    float64
Infantil       object
dtype: object

In [62]:
df['Ano'] = df['Ano'].dt.year
display(df.head())

             Filme   Ano             Genero  NotaIMDb  DuracaoMin Infantil
0     Interestelar  2014  Ficção Científica      8.70       169.0      Não
1        Toy Story  1995           Animação      8.30        81.0      Sim
2         Parasita  2019              Drama      8.50       132.0      Não
3  Divertida Mente  2015           Animação      8.39        95.0      Sim
4           Matrix  1999  Ficção Científica      8.70       136.0      Não

In [64]:
df

             Filme   Ano             Genero  NotaIMDb  DuracaoMin Infantil
0     Interestelar  2014  Ficção Científica      8.70       169.0      Não
1        Toy Story  1995           Animação      8.30        81.0      Sim
2         Parasita  2019              Drama      8.50       132.0      Não
3  Divertida Mente  2015           Animação      8.39        95.0      Sim
4           Matrix  1999  Ficção Científica      8.70       136.0      Não
5            Shrek  2001            Comédia      7.90       129.4      Sim
6      Oppenheimer  2023              Drama      8.40       180.0      Não
7           Avatar  2009  Ficção Científica      7.90       162.0      Não
8  Procurando Nemo  2003           Animação      8.20       100.0      Sim
9   Cidade de Deus  2002              Drama      8.60       130.0      Não